spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    host: localhost
    port: 13500
    database: pos_product
    username: root
    password: mongodb
    authentication-database: admin

server:
  port: 8001

app:
  storage:
    path: ${user.home}/.ijse/pos/customers